/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.Font;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.RenderingHints;
import java.awt.geom.Ellipse2D;
import javax.swing.JPanel;

/**
 *
 * @author EQUIPO
 */
public class MenuView extends javax.swing.JFrame {

    /**
     * Creates new form MenuView
     */
    public MenuView() {
        initComponents();
        aplicarEstilosModernos();
        controller.MenuController c = new controller.MenuController(this);
        this.setLocationRelativeTo(null);
        // Hacer ventana redimensionable
        this.setResizable(true);
        this.setMinimumSize(new java.awt.Dimension(800, 600));
        this.setPreferredSize(new java.awt.Dimension(1000, 700));
    }
    
    private void aplicarEstilosModernos() {
        // Header ya tiene gradiente en paintComponent
        lblHeader.setFont(new Font("Segoe UI", Font.BOLD, 28));
        lblHeader.setForeground(Color.WHITE);
        
        // Estilos de botones modernos con bordes redondeados
        aplicarEstiloBoton(btnClientes, new Color(52, 152, 219)); // Azul
        aplicarEstiloBoton(btnProductos, new Color(46, 204, 113)); // Verde
        aplicarEstiloBoton(btnProveedores, new Color(155, 89, 182)); // Morado
        aplicarEstiloBoton(btnVentas, new Color(241, 196, 15)); // Amarillo/Dorado
        aplicarEstiloBoton(btnCerrar, new Color(231, 76, 60)); // Rojo
        
        // Forzar actualización
        panelMenu.revalidate();
        panelMenu.repaint();
    }
    
    private javax.swing.JButton crearBotonRedondeado(String texto, Color colorBase) {
        javax.swing.JButton boton = new javax.swing.JButton() {
            @Override
            protected void paintComponent(Graphics g) {
                Graphics2D g2d = (Graphics2D) g;
                g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g2d.setColor(getBackground());
                g2d.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
                super.paintComponent(g);
            }
        };
        
        boton.setText(texto);
        boton.setBackground(colorBase);
        boton.setForeground(Color.WHITE);
        boton.setFont(new Font("Segoe UI", Font.BOLD, 16));
        boton.setContentAreaFilled(false);
        boton.setOpaque(true);
        boton.setBorderPainted(false);
        boton.setFocusPainted(false);
        boton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton.setPreferredSize(new java.awt.Dimension(180, 120));
        
        // Efecto hover
        final Color colorOriginal = colorBase;
        boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton.setBackground(colorOriginal.brighter());
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton.setBackground(colorOriginal);
            }
        });
        
        return boton;
    }
    
    private void aplicarEstiloBoton(javax.swing.JButton boton, Color colorBase) {
        // Los botones ya están creados con estilo, solo actualizar color si es necesario
        boton.setBackground(colorBase);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        // Panel principal con fondo con formas orgánicas
        panelMenu = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Graphics2D g2d = (Graphics2D) g;
                g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                
                // Color de fondo base (gris muy claro)
                g2d.setColor(new Color(248, 249, 250));
                g2d.fillRect(0, 0, getWidth(), getHeight());
                
                // Formas orgánicas en tonos grises profesionales (más sutiles)
                Ellipse2D.Double forma1 = new Ellipse2D.Double(-150, -100, 500, 400);
                GradientPaint grad1 = new GradientPaint(0, 0, new Color(108, 117, 125, 80), 
                                                        getWidth(), 0, new Color(73, 80, 87, 100));
                g2d.setPaint(grad1);
                g2d.fill(forma1);
                
                Ellipse2D.Double forma2 = new Ellipse2D.Double(getWidth() - 400, getHeight() - 200, 500, 450);
                g2d.setColor(new Color(52, 58, 64, 70));
                g2d.fill(forma2);
            }
        };
        panelMenu.setOpaque(true);
        
        panelHeader = new javax.swing.JPanel();
        lblHeader = new javax.swing.JLabel();
        btnClientes = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnProveedores = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Facturación - Menú Principal");
        setResizable(true);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(1000, 700));

        // Panel header con gradiente profesional
        panelHeader = new javax.swing.JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Graphics2D g2d = (Graphics2D) g;
                g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                GradientPaint gradient = new GradientPaint(
                    0, 0, new Color(52, 58, 64),
                    getWidth(), 0, new Color(33, 37, 41)
                );
                g2d.setPaint(gradient);
                g2d.fillRect(0, 0, getWidth(), getHeight());
            }
        };
        panelHeader.setOpaque(false);

        lblHeader.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(255, 255, 255));
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("MENÚ PRINCIPAL");

        // Header con GridBagLayout para centrado
        panelHeader.setLayout(new GridBagLayout());
        GridBagConstraints gbcHeader = new GridBagConstraints();
        gbcHeader.anchor = GridBagConstraints.CENTER;
        gbcHeader.weightx = 1.0;
        gbcHeader.weighty = 1.0;
        gbcHeader.insets = new Insets(30, 20, 30, 20);
        panelHeader.setPreferredSize(new java.awt.Dimension(0, 100));
        panelHeader.add(lblHeader, gbcHeader);

        // Crear botones con bordes redondeados - colores profesionales y serios
        btnClientes = crearBotonRedondeado("Clientes", new Color(73, 80, 87)); // Gris oscuro
        btnProductos = crearBotonRedondeado("Productos", new Color(52, 58, 64)); // Gris más oscuro
        btnProveedores = crearBotonRedondeado("Proveedores", new Color(108, 117, 125)); // Gris medio
        btnVentas = crearBotonRedondeado("Ventas", new Color(33, 37, 41)); // Gris muy oscuro
        btnCerrar = crearBotonRedondeado("Cerrar Sesión", new Color(220, 53, 69)); // Rojo sobrio
        btnCerrar.setPreferredSize(new java.awt.Dimension(250, 60)); // Más ancho y menos alto
        
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });

        // Usar GridBagLayout para mejor control y redimensionamiento
        panelMenu.setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        
        // Header
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.weightx = 1.0;
        gbc.weighty = 0;
        gbc.insets = new Insets(0, 0, 0, 0);
        panelMenu.add(panelHeader, gbc);
        
        // Panel de botones principales (centrado)
        JPanel panelBotones = new JPanel();
        panelBotones.setOpaque(false);
        panelBotones.setLayout(new GridBagLayout());
        GridBagConstraints gbcBtn = new GridBagConstraints();
        gbcBtn.insets = new Insets(15, 15, 15, 15);
        
        // Fila de botones principales
        gbcBtn.gridx = 0;
        gbcBtn.gridy = 0;
        gbcBtn.fill = GridBagConstraints.BOTH;
        gbcBtn.weightx = 1.0;
        gbcBtn.weighty = 1.0;
        panelBotones.add(btnClientes, gbcBtn);
        
        gbcBtn.gridx = 1;
        panelBotones.add(btnProductos, gbcBtn);
        
        gbcBtn.gridx = 2;
        panelBotones.add(btnProveedores, gbcBtn);
        
        gbcBtn.gridx = 3;
        panelBotones.add(btnVentas, gbcBtn);
        
        // Agregar panel de botones al panel principal
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 4;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.insets = new Insets(40, 40, 20, 40);
        panelMenu.add(panelBotones, gbc);
        
        // Botón cerrar (centrado)
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.gridwidth = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.weightx = 0;
        gbc.weighty = 0;
        gbc.insets = new Insets(20, 40, 40, 40);
        panelMenu.add(btnCerrar, gbc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProductosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCerrar;
    public javax.swing.JButton btnClientes;
    public javax.swing.JButton btnProductos;
    public javax.swing.JButton btnProveedores;
    public javax.swing.JButton btnVentas;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables
}
